version: '3.2'

services:
    db:
        build: ./setup/postgres
        restart: always
        volumes:
            - /var/lib/postgres/data:/var/lib/postgres/data
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 15432:5432

    python:
        build: .
        working_dir: /usr/src/app
        command: python app/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
            - /etc/localtime:/etc/localtime:ro
        links:
            - db:db
        depends_on:
            - db

    proxy:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./setup/nginx:/etc/nginx:ro
            - ./log/nginx:/var/log/nginx:rw
            - /etc/localtime:/etc/localtime:ro
        environment:
            TZ: Asia/Tokyo
        links:
            - python:python
