version: '3.2'

services:
    db:
        image: postgres
        restart: always
        volumes:
            - /var/lib/postgres/data:/var/lib/postgres/data
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5432:5432

    python:
        build: .
        working_dir: /var/www/app/app
        command: gunicorn app:app -b 0.0.0.0:8000 --config gunicorn_conf.py
        volumes:
            - .:/var/www/app
            - /etc/localtime:/etc/localtime:ro
        links:
            - db:db
        depends_on:
            - db

    proxy:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./setup/nginx:/etc/nginx:ro
            - ./log/nginx:/var/log/nginx:rw
            - /etc/localtime:/etc/localtime:ro
        environment:
            TZ: Asia/Tokyo
        links:
            - python:python
